app/search/forms.py
from flask import request
from flask_wtf import FlaskForm
from flask_babel import lazy_gettext as _l
from wtforms import StringField, BooleanField, SelectMultipleField, SubmitField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    simple_q = StringField(_l('Suche'), validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)


class AdvancedSearchForm(SearchForm):
    simple_q = StringField(_l('Suche'))  # query string is not DataRequired here since someone might want to search on other criteria
    identifier = StringField(_l('Bezeichnung/Signatur'))
    orig_place = StringField(_l('Entstehungsort'))
    orig_place_cert = SelectMultipleField(_l('Sicherheit'),  choices=[('', ''),
                                                                      ('high', _l('Hoch')),
                                                                      ('medium', _l('Mittel')),
                                                                      ('low', _l('Niedrig'))])
    orig_year_start = StringField(_l('Jahr'))
    orig_year_end = StringField(_l('Jahr'))
    ms_item = StringField(_l('Inhalt'))
    person = StringField(_l('Personen'))
    person_role = SelectMultipleField(_l('Role'),  choices=[('', ''), ('Abt', _l('Abt')),
                                                                      ('Schreiber', _l('Schreiber'))])
    provenance = StringField(_l('Provenienz'))
    with_digitalisat = BooleanField(_l('Nur Handschriften mit Digitalisate'))
    with_scribe = BooleanField(_l('Nur Handschriften mit genannten Schreibern'))
    with_illuminations = BooleanField(_l('Nur illuminierte Handschriften'))
    with_exlibris = BooleanField(_l('Nur Handschriften mit "exlibris" Notierung'))
    with_tironoten = BooleanField(_l('Nur Handschriften mit tironischen Noten'))
    with_neumierung = BooleanField(_l('Nur neumierte Handschriften'))
    with_ink_analysis = BooleanField(_l('Nur Handschriften mit Tintenanalyse'))
    submit = SubmitField(_l('Suche Durchführen'), id="advancedSearchSubmit")

app/search/__init__.py
from flask import Blueprint

bp = Blueprint('search', __name__)

from app.search import routes

app/search/routes.py
from flask import redirect, request, url_for, g, flash, current_app, render_template
from flask_babel import _
from .Search import advanced_query_index
from .forms import AdvancedSearchForm
from app.search import bp
from json import dumps


HIGHLIGHT_MAPPING = {'identifier.id': _('Signatur'),
                     'ms_item': _('Inhalt'),
                     'provenance': _('Geschichte der Handschrift'),
                     'person.name': _('Name'),
                     'orig_place.place': _('Ort'),
                     'orig_place.source': _('Quelle'),
                     'person.role': _('Role'),
                     'person.identifier': _('ID'),
                     'orig_place.cert': _('Sicherheit'),
                     'person': _('Person'),
                     'orig_place': _('Entstehungsort'),
                     'with_digitalisat': _('Digitalisate')
                     }


@bp.route("/simple", methods=["GET"])
def r_simple_search() -> redirect:
    if not g.search_form.validate():
        for k, m in g.search_form.errors.items():
            if k == 'simple_q':
                flash(m[0] + _(' Die einfache Suche funktioniert nur mit einem Suchwort.'))
        return redirect(url_for('.r_results', source='simple', simple_q=g.search_form.data['simple_q']))
    data = g.search_form.data
    return redirect(url_for('.r_results', source='simple', sort="_id", **data))


@bp.route("/results", methods=["GET"])
def r_results():
    source = request.args.get('source', None)
    # This means that someone simply navigated to the /results page without any search parameters
    if not source:
        return redirect(url_for('main.index'))
    posts_per_page = 10000
    page = 1
    search_args = dict(simple_q=request.args.get('simple_q'),
                       identifier=request.args.get('identifier'),
                       orig_place=request.args.get('orig_place'),
                       orig_place_cert=request.args.get('orig_place_cert', '').split('+'),
                       orig_year_start=request.args.get('orig_year_start'),
                       orig_year_end=request.args.get('orig_year_end'),
                       ms_item=request.args.get('ms_item'),
                       person=request.args.get('person'),
                       person_role=request.args.get('person_role', '').split('+'),
                       person_identifier=request.args.get('person_identifier'),
                       provenance=request.args.get('provenance'),
                       with_digitalisat=request.args.get('with_digitalisat'),
                       with_scribe=request.args.get('with_scribe'),
                       with_illuminations=request.args.get('with_illuminations'),
                       with_exlibris=request.args.get('with_exlibris'),
                       with_tironoten=request.args.get('with_tironoten'),
                       with_neumierung=request.args.get('with_neumierung'),
                       with_ink_analysis=request.args.get('with_ink_analysis'),
                       sort=request.args.get('sort', '_id'))
    posts, total, aggs = advanced_query_index(**search_args)
    return render_template('search/search.html', title=_('Suche'), posts=posts, current_page=page,
                           total_results=total, aggs=aggs, highlight_mapping=HIGHLIGHT_MAPPING)


@bp.route("/advanced_search", methods=["GET"])
def r_advanced_search():
    form = AdvancedSearchForm()
    data_present = [x for x in form.data if form.data[x]]
    if form.validate() and data_present and 'submit' in data_present:
        data = form.data
        for k, v in data.items():
            if isinstance(v, list):
                data[k] = '+'.join(v)
        return redirect(url_for('.r_results', source="advanced", **data))
    for k, m in form.errors.items():
        flash(k + ': ' + m[0])
    return render_template('search/advanced_search.html', form=form)

app/templates/search/advanced_search.html
{% extends "container.html" %}
{% block title %}{{ _('Erweiterte Suche') }}{% endblock %}

{% block body %}
        <!-- BODY OF THE SEARCH PAGE - 1st row = title. -->
        <form action="" method="get" id="advanced-form">
            {{ form.hidden_tag() }}
            <div class="text-center"><h3><strong>{{ _('Erweiterte Suche') }}</strong></h3></div>
            <div class="row justify-content-center pt-2">{{ form.submit(size=32, class="btn btn-lg btn-secondary") }}</div>
            <br>
        <!-- 2d row = search entries. -->
            <div class="row justify-content-center">
                <div class="col-4">
                    <div class="form-group mb-2">
                        <div class="text-center search-section-label"><strong><label for="word-search-box">{{ _('Allgemeine Wortsuche') }}</label></strong></div>
                        <div>
                            {{ form.simple_q(class="form-control my-0", placeholder=form.simple_q.label.text, id="word-search-box", list="word-search-datalist", default=form.simple_q.label.text, autocomplete="off") }}
                            <datalist id="word-search-datalist">
                            </datalist>
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        <div class="text-center search-section-label"><strong>{{ form.identifier.label }}</strong></div>
                        <div>
                            {{ form.identifier(class="form-control my-0", placeholder=form.identifier.label.text, id="identifier-search-box", list="identifier-search-datalist", default=form.identifier.label.text, autocomplete="off") }}
                            <datalist id="identifier-search-datalist">
                            </datalist>
                        </div>
                    </div>
                    <div class="text-center search-section-label"><strong>{{ _('Entstehungsortssuche') }}</strong></div>
                    <div class="form-group form-row mb-2 align-items-center">
                        <div class="col-auto">
                            <div class="text-center search-section-label">{{ _('Ortsname') }}</div>
                        </div>
                        <div class="col">
                            <div>
                                {{ form.orig_place(class="form-control my-0", placeholder=form.orig_place.label.text, id="orig_place-search-box", list="orig_place-search-datalist", default=form.orig_place.label.text, autocomplete="off") }}
                                <datalist id="orig_place-search-datalist">
                                </datalist>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-row mb-2">
                        <div class="col-auto">
                            <div class="text-center search-section-label">{{ form.orig_place_cert.label }}</div>
                        </div>
                        <div class="col">
                            <div>
                            {% for c in form.orig_place_cert.choices[1:] %}
                                <div class="form-check form-check-inline form-group mb-0">
                                    <input class="form-check-input" id="orig_place_cert_{{ c[0] }}" name="orig_place_cert" type="checkbox" value="{{ c[0] }}">
                                    <label class="form-check-label" for="orig_place_cert_{{ c[0] }}">{{ c[1] }}</label>
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="text-center search-section-label"><strong>{{ _('Entstehungszeitsuche') }}</strong></div>
                    <div class="form-group mb-2">
                        <div class="form-row align-items-center justify-content-center">
                            <div class="date-range-label">{{ _('Von') }}</div>
                            <div class="form-group ml-2">
                                <div class="text-center">{{ form.orig_year_start.label }}</div>
                                {% if form.orig_year_start.errors %}
                                {{ form.orig_year_start(size=4, class="invalid-field form-control") }}
                                {% else %}
                                {{ form.orig_year_start(size=4, class="form-control") }}
                                {% endif %}
                            </div>
                            <div class="date-range-label">{{ _('Bis') }}</div>
                            <div class="form-group ml-2">
                                <div class="text-center">{{ form.orig_year_end.label }}</div>
                                {% if form.orig_year_end.errors %}
                                {{ form.orig_year_end(size=4, class="invalid-field form-control") }}
                                {% else %}
                                {{ form.orig_year_end(size=4, class="form-control") }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        <div class="text-center search-section-label"><strong>{{ _('Manuskriptinhalt') }}</strong></div>
                        <div>
                            {{ form.ms_item(class="form-control my-0", placeholder=form.ms_item.label.text, id="ms_item-search-box", list="ms_item-search-datalist", default=form.ms_item.label.text, autocomplete="off") }}
                            <datalist id="ms_item-search-datalist">
                            </datalist>
                        </div>
                    </div>
                    <div class="text-center search-section-label"><strong>{{ _('Personensuche') }}</strong></div>
                    <div class="form-group form-row mb-2 align-items-center">
                        <div class="col-auto">
                            <div class="text-center search-section-label">{{ _('Personenname') }}</div>
                        </div>
                        <div class="col">
                            <div>
                                {{ form.person(class="form-control my-0", placeholder=form.person.label.text, id="person-search-box", list="person-search-datalist", default=form.person.label.text, autocomplete="off") }}
                                <datalist id="person-search-datalist">
                                </datalist>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-row mb-2">
                        <div class="col-auto">
                            <div class="text-center search-section-label">{{ form.person_role.label }}</div>
                        </div>
                        <div class="col">
                            <div>
                            {% for c in form.person_role.choices[1:] %}
                                <div class="form-check form-check-inline form-group mb-0">
                                    <input class="form-check-input" id="person_role_{{ c[0] }}" name="person_role" type="checkbox" value="{{ c[0] }}">
                                    <label class="form-check-label" for="person_role_{{ c[0] }}">{{ c[1] }}</label>
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        <div class="text-center search-section-label"><strong>{{ form.provenance.label }}</strong></div>
                        <div>
                            {{ form.provenance(class="form-control my-0", placeholder=form.provenance.label.text, id="provenance-search-box", list="provenance-search-datalist", default=form.provenance.label.text, autocomplete="off") }}
                            <datalist id="provenance-search-datalist">
                            </datalist>
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        <div class="text-center search-section-label"><strong>{{ _('Suche eingrenzen') }}</strong></div>
                        <div class="form-check form-check-inline form-group mb-0">
                            <input class="form-check-input" id="with_digitalisat_checkbox" name="with_digitalisat" type="checkbox" value="true">
                            <label class="form-check-label" for="with_digitalisat_checkbox">{{ form.with_digitalisat.label.text }}</label>
                        </div>
                        <div class="form-check form-check-inline form-group mb-0">
                            <input class="form-check-input" id="with_scribe_checkbox" name="with_scribe" type="checkbox" value="true">
                            <label class="form-check-label" for="with_scribe_checkbox">{{ form.with_scribe.label.text }}</label>
                        </div>
                        <div class="form-check form-check-inline form-group mb-0">
                            <input class="form-check-input" id="with_illumination_checkbox" name="with_illuminations" type="checkbox" value="true">
                            <label class="form-check-label" for="with_illumination_checkbox">{{ form.with_illuminations.label.text }}</label>
                        </div>
                        <div class="form-check form-check-inline form-group mb-0">
                            <input class="form-check-input" id="with_neumierung_checkbox" name="with_neumierung" type="checkbox" value="true">
                            <label class="form-check-label" for="with_neumierung_checkbox">{{ form.with_neumierung.label.text }}</label>
                        </div>
                        <div class="form-check form-check-inline form-group mb-0">
                            <input class="form-check-input" id="with_tironoten_checkbox" name="with_tironoten" type="checkbox" value="true">
                            <label class="form-check-label" for="with_tironoten_checkbox">{{ form.with_tironoten.label.text }}</label>
                        </div>
                        <div class="form-check form-check-inline form-group mb-0">
                            <input class="form-check-input" id="with_exlibris_checkbox" name="with_exlibris" type="checkbox" value="true">
                            <label class="form-check-label" for="with_exlibris_checkbox">{{ form.with_exlibris.label.text }}</label>
                        </div>
                        <div class="form-check form-check-inline form-group mb-0">
                            <input class="form-check-input" id="with_ink_analysis_checkbox" name="with_ink_analysis" type="checkbox" value="true">
                            <label class="form-check-label" for="with_ink_analysis_checkbox">{{ form.with_ink_analysis.label.text }}</label>
                        </div>
                    </div>
                </div>
            </div>
        </form>
{% endblock %}

app/templates/search/search.html
{% extends "container.html" %}
{% block title %}Coenotur: {{ _('Suchergebnisse') }}{% endblock %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-8">
    <article class="container-fluid">
    <header>
    {% if total_results['value'] > 0 %}
            <h1>{{ _('Suchergebnisse') }}: {{ total_results['value']|string }} {{ _(' Treffer aus') }} <span id="aggs-all-docs" data-toggle="tooltip" data-container="#aggs-all-docs" title="{{ _('Die Gesamtzahl der Dokumente in den gewählten Corpora.') }}">{{ aggs['all_docs']['doc_count']|string }}</span> {{ _('Dokumenten') }}</h1>
        
    
    {% else %}
    <h1>{{ _('Suchergebnisse') }} ({{ total_results['value']|string }} {{ _(' Treffer') }})</h1>
    {% endif %}
    </header>
    {% if posts|length == 0 %}
    <h4>{{ _("Keine Ergebnisse") }}</h4>
    {% endif %}
    {% set path_no_sort %}{% for r in request.args %}{% if r != 'sort' %}{{ r }}={{ request.args.get(r)|replace('+', '%2B') }}&{% endif %}{% endfor %}{% endset %}
    <table id="partsSearchResultTable" class="table table-sm table-hover table-bordered" aria-label="{{ _('Suchergebnisse') }}">
        <thead>
            <tr>
                <th id="results-text-column" scope="col">{{ _('Text') }}</th>
                <th id="results-date-column" scope="col">{{ _('Entstehungszeit') }} <a href="{{ url_for('search.r_results') + '?' + path_no_sort }}sort=date_asc">↑</a> <a href="{{ url_for('search.r_results') + '?' + path_no_sort }}sort=date_desc">↓</a></th>
                <th id="results-place-column" scope="col">{{ _('Entstehungsort') }}</th>
                <th id="results-contents-column" scope="col">{{ _('Inhalt') }}</th>
                <th id="results-title-column" scope="col">{{ _('Manuskript') }} <a href="{{ url_for('search.r_results') + '?' + path_no_sort }}sort=_id">↑</a></th>
            </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr>
                <td>
                    {% if 'highlight' in post %}
                    {% for k, v in post['highlight'].items() %}
                    <p class="card-text m-0"><u>{{ highlight_mapping[k] }}</u></p>
                    {% for h in v %}
                        {% if k == 'with_digitalisat' %}
                        <p class="card-text m-0"><small>- <a href="{{ h|striptags }}" target="_blank">{{ h|safe }}</a></small></p>
                        {% else %}
                        <p class="card-text m-0"><small>- {{ h|safe }}</small></p>
                        {% endif %}
                    {% endfor %}
                    {% endfor %}
                    {% endif %}
                    {% if 'inner_hits' in post %}
                    {% for k, v in post['inner_hits'].items() %}
                        <p class="card-text m-0"><u>{{ highlight_mapping[k] }}</u></p>
                        
                        {% for h in v['hits']['hits'] %}
                        <p class="card-text m-0"><small>
                            {% for sub_k, sub_v in h['_source'].items() %}
                                {% if k + '.' + sub_k in h['highlight'] %}
                                    {% if not loop.first %}/ {% endif %}{{ highlight_mapping[k + '.' + sub_k] + ': ' + h['highlight'][k + '.' + sub_k]|join(',')|safe }}
                                {% else %}
                                    {% if sub_v %}
                                    {% if not loop.first %}/ {% endif %}{{ highlight_mapping[k + '.' + sub_k] + ': ' + sub_v }}
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </small></p>
                        {% endfor %}
                    {% endfor %}
                    {% endif %}
                </td>
                <td>{% if post['_source']['date_string']|trim %}{{ post['_source']['date_string'] }}{% endif %}</td>
                <td>{% for p in post['_source']['orig_place'] %}{% if p['place']|trim %}{% if not loop.first
                    %}<br>{% endif %}- {{
                    p['place'] }}{% if p['source']|trim %} ({{ p['source']|upper|replace('_', ' ') }}){% endif %}{%
                    endif
                    %}{% endfor
                    %}</td>
                <td>{% if post['_source']['ms_item']|trim %}- {{ post['_source']['ms_item']|join('<br>- ')|safe }}{%
                    endif
                    %}</td>
                <td data-order="{{ loop.index }}"><a class="internal-link"
                                                     href="{{ url_for('main.handschrift', manuscript=post['_id']+'.xml') }}">{{ post['_source']['signature'] }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </article>
    </div>
</div>
{% endblock %}

app/templates/search/search_box.html
{% if g.search_form and 'advanced_search' not in request.url %}
<form id="simple-search-form" class="form mb-0" method="get" action="{{ url_for('search.r_simple_search') }}">
    <div class="form-row">
        {{ g.search_form.simple_q(size=25, class="form-control my-0", placeholder=g.search_form.simple_q.label.text, id="simple-search-q", list="simple-search-datalist", autocomplete="off") }}
        <datalist id="simple-search-datalist">
        </datalist>
    </div>
    <div class="form-row justify-content-between">
        <a id="advanced-search-link-tooltip" data-toggle="tooltip" data-container="#advanced-search-link-tooltip" class="nav-link text-white p-0 text-right relative-position" href="{{ url_for('search.r_advanced_search') }}" title="{{ _('Zur Seite der erweiterten Suche') }}">{{ _('Erweiterte Suche') }}</a>
    </div>
</form>
{% endif %}